plugins:
  babble_enabled:
    default: true
    client: true
  babble_placeholder:
    default: ""
    client: true
  babble_icon:
    default: "bullhorn"
    client: true
  babble_page_size:
    default: 100
    client: true
